### ISSUE TITLE
Translation of Chinese 

### ISSUE THREAD

**Issue by anbangli** [highperformancecoder/scidavis-old#123]
<! Please file Feature requests at https://sourceforge.net/p/scidavis/scidavis-feature-requests/>

**Is your feature request related to a problem? Please describe.**
I am a Chinese user and I found that there is no translation file of Chinese.

**Describe the solution you'd like**
I would like to do the translation to Chinese. I am learning to use Qt linguist. But I did not know how to prepare a template file for Chinese. Please provide such a template file, and I would like to do the translation.

**Comment by highperformancecoder** [comment]
[scidavis_zh.ts.log](https://github.com/highperformancecoder/scidavis/files/3219113/scidavis_zh.ts.log)

Attached please find an empty template. Remove the .log extension - I had to add that to allow github to upload the file. Also note that a wen li is also attempting a translation at this time (liwenbus@gmail.com). Please coordinate with him. If one of you were to send me even a partially translated file, I will add it to the scidavis source code on Github, and then you can use git to collaborate.

**Comment by anbangli** [comment]
Thanks! I will coordinate with Wen Li to do the translation.

**Comment by anbangli** [comment]
I contacted with Wen Li. He/she has finished more than a half of the translation work. And I helped to finished the remaining translations. Here attached the translation files:

[scidavis_zh_CN.ts.log]  -- Simplified-Chinese (https://github.com/highperformancecoder/scidavis/files/3226218/scidavis_zh_CN.ts.log)

[scidavis_zh_TW.ts.log]  -- Tranditional-Chinese
(https://github.com/highperformancecoder/scidavis/files/3226219/scidavis_zh_TW.ts.log)

**Comment by highperformancecoder** [comment]
Thank you for this. I have integrated the translation into the source code.
