### ISSUE TITLE
Plot/Axis title can not use capital letters

### ISSUE THREAD

**Issue by minghuajun** [highperformancecoder/scidavis-old#124]
<! Please file bug reports at: https://sourceforge.net/p/scidavis/scidavis-bugs/> 

**Describe the bug**
My computer OS is macOS.
I intalled the software by **scidavis-1.25-mac-dist.dmg**.
When I changed the title of axis, it can not use the capital letters.

**Comment by highperformancecoder** [comment]
Works for me on 1.25 built on openSUSE Tumbleweed... I can't check it on the Mac for another couple of weeks...

In the meantime, could you please raise this as a ticket on SourceForge, and close this Github issue? It will most likely languish here...
