### ISSUE TITLE
Scidavis segfaults when Python is selected as the scripting language

### ISSUE THREAD

**Issue by ghost** [highperformancecoder/scidavis-old#129]
**Describe the bug**
I just installed Scidavis on an install of Elementary (Ubuntu 18.04-based) from the repos (went through the steps for adding the package repos, [listed here](https://software.opensuse.org//download.html?project=home%3Ahpcoder1&package=scidavis)).

Please note that this is my first time using Scidavis and I was just exploring the program, seeing what features it has, so I'm not sure if I was supposed to install something else alongside.

**To Reproduce**
1. Install Scidavis on Elementary OS and run
2. In the toolbar: Scripting -> Scripting Language -> (opens dialog) -> Python -> OK
3. Program shuts down and "Segmentation fault" is displayed in the terminal that it was ran from.

**Expected behavior**
Not quite sure what is actually supposed to occur, as this is my first time using it. I was hoping it would have a place to type in some Python to generate some column data.

**Screenshots**
Here's the window it crashes on.
![image](https://user-images.githubusercontent.com/4730591/65470798-906f2180-de21-11e9-8297-31ea98eb93fe.png)

**Desktop**
 - Device: Thinkpad X1
 - OS: Elementary OS Juno, Ubuntu 18.04.2 LTS, Linux 4.15.0-45-generic
- GTK+ 3.22.30
Version screenshot: 
![image](https://user-images.githubusercontent.com/4730591/65470846-c01e2980-de21-11e9-9800-83b33078c743.png)

**Comment by ghost** [comment]
Here's the entirety of what gets displayed:

```kevin@kevin-thinkpad:~/Projects$ scidavis
Gtk-Message: 16:51:41.178: Failed to load module "pantheon-filechooser-module"

(scidavis:23128): Gtk-WARNING **: 16:51:41.198: Unable to locate theme engine in module_path: "pixmap",

(scidavis:23128): Gtk-WARNING **: 16:51:41.199: Unable to locate theme engine in module_path: "pixmap",

(scidavis:23128): Gtk-WARNING **: 16:51:41.199: Unable to locate theme engine in module_path: "pixmap",

(scidavis:23128): Gtk-WARNING **: 16:51:41.199: Unable to locate theme engine in module_path: "pixmap",
Segmentation fault
```

**Comment by Fellypao** [comment]
HI @kevinhikaruevans ,
This is a bug in the Ubuntu package you installed - which looks to happen in almost all (x)Ubuntu versions. It was already reported in:
https://sourceforge.net/p/scidavis/scidavis-bugs/386/

**Comment by ghost** [comment]
Thanks for the response. I will probably look into it later this week, if it hasn't been fixed yet in master.

**Comment by kevinhikaruevans** [comment]
Thanks for the response. I will probably look into it later this week, if it hasn't been fixed yet in master.

**Comment by highperformancecoder** [comment]
I can reproduce this issue, not only on Ubuntu, but on OpenSUSE Tumbleweed. Since this issue is open on the SF tracker, I'll close this one.

**Comment by Fellypao** [comment]
@kevinhikaruevans 
If you don't know yet, there is a solution for the issue here:
https://sourceforge.net/p/scidavis/scidavis-bugs/386/
