### ISSUE TITLE
Linux Compiler Environment

### ISSUE THREAD

**Issue by ghost** [highperformancecoder/scidavis-old#137]
I try to use Ubuntu 18.04, 16.04, 14.04, and centos 7 without matching libqwt5-qt5 package, which linux distribution version should I use to compile? (opensuse?)

Thank you

**Comment by topkinschen** [comment]
I tried the newest v2.2.0, but fail to build becuase missing of lots of header file of 3th party lib.

in previous document:https://highperformancecoder.github.io/scidavis-handbook/requirements.html,lists all depandency lib versions.
but the newest INSTALL document not listed clearly. could you please give the lib version:
    Qt version 5   : 5.4? 5.9?5.12?5.14?
    Qwt version 5 : which version? 5.x?  6.x?
    QwtPlot3D   : which version? 
    GSL             : which version? 
    muParser    : which version? 
    zlib             : which version? 

For the optional Python scripting feature, you also need:

    Python version 3   : which version? 
    PyQt                     : which version? 
    sip                        : which version? 

please help. thanks.

**Comment by highperformancecoder** [comment]
On Mon, Jun 01, 2020 at 05:52:52PM -0700, topkinschen wrote:
> I tried the newest v2.2.0, but fail to build becuase missing of lots of header
> file of 3th party lib.
> 
> in previous document:https://highperformancecoder.github.io/scidavis-handbook/
> requirements.html,lists all depandency lib versions.
> but the newest INSTALL document not listed clearly. could you please give the
> lib version:
> Qt version 5 : 5.4? 5.9?5.12?5.14?

5.x - tested against 5.14.1

> Qwt version 5 : which version? 5.x? 6.x?

5.x, obviously. You need the patched source code from the qwt5-qt5 package.

> QwtPlot3D : which version?

tested against 0.2.7

> GSL : which version?

2.x - tested against 2.6

> muParser : which version?

2.x - tested against 2.2.4

> zlib : which version?
>

1.x - tested against 1.2.11


> For the optional Python scripting feature, you also need:
> 
> Python version 3   : which version?

3.x - tested against 3.8.2

> PyQt                     : which version?

tested against 5.13.2

> sip                        : which version?
>

tested against 4.19.19

> please help. thanks.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*
> 

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     hpcoder@hpcoders.com.au
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by topkinschen** [comment]
thanks!thanks!

**Comment by highperformancecoder** [comment]
You can obtain a copy of libqwt5-qt5 from
https://build.opensuse.org/package/show/home:hpcoder1/libqwt5-qt5

Alternatively, you can build it from source code at
https://github.com/gbm19/qwt5-qt5

Note scidavis 2.x doesn't build on Ubuntu earlier than 17.10.

On Mon, Jun 01, 2020 at 05:35:34AM -0700, yousabuk wrote:
> I try to use Ubuntu 18.04, 16.04, 14.04, and centos 7 without matching
> libqwt5-qt5 package, which linux distribution version should I use to compile?
> (opensuse?)
> 
> Thank you
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*
> 

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     hpcoder@hpcoders.com.au
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------
