### ISSUE TITLE
Minimum Qt supported version.

### ISSUE THREAD

**Issue by ghost** [highperformancecoder/scidavis-old#148]
Recently, I have seen a commit that fix compilation with Qt 5.9 (Ubuntu 18.04), so I am asking about minimum supported version of Qt, and what is the policy for that?
Is it about Ubuntu LTS?

**Comment by highperformancecoder** [comment]
On Tue, Jul 14, 2020 at 01:19:28AM -0700, مهدي شينون (Mehdi Chinoune) wrote:
> Recently I have seen a commit that fix compilation with Qt 5.9 (Ubuntu 18.04),
> so I am asking about minimum supported version of Qt, and what is the policy
> for that?
> Is it about Ubuntu LTS?

I'm not sure we have one, but we do still need to support 18.04 for a while yet.
We've only really dropped 14.04 support recently.

20.04 is an LTS, so maybe we could formalise it as supporting current
LTS and back to the previous LTS, so dropping 18.04 when 22.04 is
released.

But if it's too problematic for us (you're basically 1 of 3, so we
don't have much developer support), then by all means dropping suport
for older release should be considered.


-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     hpcoder@hpcoders.com.au
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by ChinouneMehdi** [comment]
Thanks, I will try to test building on Ubuntu 18.04 before push any changes.

**Comment by ghost** [comment]
Thanks, I will try to test building on Ubuntu 18.04 before push any changes.
