### ISSUE TITLE
Compile errors on new qt5 versions

### ISSUE THREAD

**Issue by joequant** [highperformancecoder/scidavis-old#152]
<! Please file bug reports at: https://sourceforge.net/p/scidavis/scidavis-bugs/> 

**Describe the bug**
I'm getting compile errors on new qwt-qt5 version. Error messages such as 

src/Legend.h:36:10: fatal error: qwt_array.h: No such file or directory
   36 | #include <qwt_array.h>
      |          ^~~~~~~~~~~~~
src/PlotEnrichement.h:73:10: error: 'QwtDoubleRect' does not name a type
   73 |  virtual QwtDoubleRect boundingRect() const;
      |          ^~~~~~~~~~~~~

**To Reproduce**

Compiile against qwt-qt5 6.1.5

**Expected behavior**

Expect no compile errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux

**Smartphone (please complete the following information):**

**Additional context**

**Comment by highperformancecoder** [comment]
Compiile against qwt-qt5 6.1.5

This is probably your problem. SciDAVis is currently only builds against Qwt5, not Qwt6. You need the qwt5-qt5-dev(or possibly libqwt5-qt5-devel depending on distro) package.

I had a brief foray into prting SciDAVis to Qwt6, but it is a big job, not helped by the fact that Qwt6 has a much worse API than Qwt5. There needs to be all sorts of shimming involved to create a sane API.
