### ISSUE TITLE
Can not build with sip5

### ISSUE THREAD

**Issue by lbartoletti** [highperformancecoder/scidavis-old#154]
<! Please file bug reports at: https://sourceforge.net/p/scidavis/scidavis-bugs/> 

**Describe the bug**

scidavis can not be built with sip5 because of deprecated sipconfig module.

**To Reproduce**

Try to build with sip5.

**Expected behavior**
Can be built with sip5.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] FreeBSD with sip5 branch (not yet released in FreeBSD packages) https://github.com/freebsd/freebsd-ports-kde/pull/74

**Smartphone (please complete the following information):**

**Additional context**

I'm trying to update sip from 4.x to 5.x on FreeBSD.
This has already been fixed on some softwares like [QGIS](https://github.com/qgis/qgis/), [Calibre](https://github.com/kovidgoyal/calibre), etc.

**Comment by highperformancecoder** [comment]
The plan is to abandon PyQt and SIP altogether, in favour of Classdesc, which has a better chance of support on Windows. Code is in the classdesc-python branch. Unfortunately (lack of time, bla, bla), I have had any time to work on this this year, and 'm not sure when I'll get to it.
