### ISSUE TITLE
Problems with refactored cmake file (for liborigin)

### ISSUE THREAD

**Issue by alxpl** [highperformancecoder/scidavis-old#218]
While trying to build liborigin with all the latest changes, I came across a few issues.

First, in liborigin.pc.in, the version string is made up by a concatenation of variables:
`Version: @LIBORIGIN_VERSION_MAJOR@.@LIBORIGIN_VERSION_MINOR@.@LIBORIGIN_VERSION_BUGFIX@`
However, these variables no longer exist; CMakeLists.txt now has this in their place:
```
project( liborigin
  VERSION 3.0.0
  LANGUAGES CXX
  )
```
As a result, the version ends up being "..", which causes rpm to produce this baffling error message:
`error: Illegal sequence ".." in: ..`
I would submit a PR, but i don't know what you might prefer to keep. Personally I'd go with the variables.

Second, even though I set the target to "origin_shared" (took me quite some time to figure out it had changed from "origin", it would be nice™ if such changes were documented someplace the moment they were made), the static library gets built and installed along with the dynamic one, so I had to manually delete it in my spec file.

With these changes in place, liborigin builds fine, so I can finally move on to SciDAVis itself, probably sometime later in the week. Once these glitches get fixed, someone should push them upstream.

**Comment by gerlachs** [comment]
liborigin.pc should now be fixed upstream. I also added options to disable shared and static libraries.
Please let me know if that works for you.

**Comment by alxpl** [comment]
Everything is fixed in liborigin version 3.0.1.
