### ISSUE TITLE
minigzip shared object in 2.4.0

### ISSUE THREAD

**Issue by alxpl** [highperformancecoder/scidavis-old#221]
Yesterday I submitted the 2.4.0 updates to Fedora 33, 34 and Rawhide branches. However, the update can't get installed, because somewhere along the way, SciDAVis picked up a runtime dependency on minigzip:
```
 Problem 1: cannot install the best update candidate for package scidavis-2.3.0-4.fc34.x86_64
  - nothing provides libminigzip.so()(64bit) needed by scidavis-2.4.0-1.fc34.x86_64
```
Looking at the [build logs](https://kojipkgs.fedoraproject.org//packages/scidavis/2.4.0/1.fc34/data/logs/x86_64/build.log), I saw the dependency discovered by rpm:
```
Requires: […] libminigzip.so()(64bit) […]
```
During the build phase, it appears that several parts of the program, e.g. the fit plugins are getting linked to a libminigzip.so. This didn't happen in [2.3.0](https://kojipkgs.fedoraproject.org//packages/scidavis/2.3.0/3.fc34/data/logs/x86_64/build.log). That shared object file is present in the build directory, but it doesn't get installed anywhere afterwards.

What is happening here? Is minigzip even necessary, from the moment there's a dependency on zlib?

**Comment by alxpl** [comment]
I think I've managed to replicate the old behavior by building minigzip as a static library. In /3rdparty/CMakeLists.txt I've changed this [line](https://github.com/highperformancecoder/scidavis/blob/ca0361d9ad2459c56daf6401c934c4a3ec1494ac/3rdparty/CMakeLists.txt#L7):
`add_library( minigzip "minigzip/minigzip.c" `
to this:
`add_library( minigzip STATIC "minigzip/minigzip.c" )`
The built binaries don't require libminigzip.so anymore, the scidavis package can be installed/upgraded and I can create and open compressed project files (.sciprj.gz) without any problems.

Does this look like an acceptable/correct solution?

**Comment by highperformancecoder** [comment]
On Thu, May 13, 2021 at 03:52:51AM -0700, alxpl wrote:
> I think I've managed to replicate the old behavior by building minigzip as a
> static library. In /3rdparty/CMakeLists.txt I've changed this line:
> add_library( minigzip "minigzip/minigzip.c"
> to this:
> add_library( minigzip STATIC "minigzip/minigzip.c" )
> The built binaries don't require libminigzip.so anymore, the scidavis package
> can be installed/upgraded and I can create and open compressed project files
> (.sciprj.gz) without any problems.
> 
> Does this look like an acceptable/correct solution?

Looks good to me.



-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     ***@***.***
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by alxpl** [comment]
I accidentally abused my newfound powers and [committed](https://github.com/SciDAVis/scidavis/commit/247c8c6c64c2a9381e7252f7a6d49d7c0d3f3d07) it to the new project repo.

Is it possible to migrate issues and discussions over there as well?
