### ISSUE TITLE
Why does SciDAVis need pieces of liborigin installed on /usr/local?

### ISSUE THREAD

**Issue by Fellypao** [highperformancecoder/scidavis-old#40]
Since SciDAVis uses a static liborigin library, I believe that the liborigin files in:
/usr/local/share/doc/liborigin/
/usr/local/include/liborigin/
and files:
/usr/local/lib/liborigin.*
/usr/local/bin/opj2dat
should not be installed on the system **during SciDAVis compilation**. It is not a good practice!
Of course, some of those files, like documentation, could be installed as part of the SciDAVis package, but not independently of it.
The liborigin.a file generated in 3rdparty/liborigin/ dir is not enough to build and run SciDAVis with Origin import support?

**Comment by highperformancecoder** [comment]
I agree. It should not be installing such. Probably a bizarro qmake error.

**Comment by highperformancecoder** [comment]
I usually do "make install" from the scidavis executable directory, as
this is the only thing that needs to be installed.

By default, the qmake generated Makefile will recursively do make
install in all directories - is there a way of disabling that feature?


-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------
