### ISSUE TITLE
Dynamic data loading

### ISSUE THREAD

**Issue by SimoneTosato** [highperformancecoder/scidavis-old#46]
Is it possible to load data dynamically? 
The project i'm currently working on reads a stream of data, i would love to use scidavis to work on them and it would be intresting to update/reload the data every x minutes automatically. Is this possible somehow? Maybe using python, but i'm quite new to scidavis so i don't know how to do this.

**Comment by Fellypao** [comment]
Of course. Using python almost everything is possible :)
In the attachment there is an example of how you can do it (to be executed in a SciDAVis note).
I'm not an expert in using python. Then, I think that this code can be improved.
For more information about python is SciDAVis see: https://highperformancecoder.github.io/scidavis-handbook/sec-python.html
SciDAVis has a forum at: https://sourceforge.net/p/scidavis/discussion/ . So, in the next time, please post this kind of question there. Then it can be seen by other users.
Notice that python scripting works only on Linux and Mac.
Best regards.
[python_code_to_run_in_SciDAVis.txt](https://github.com/highperformancecoder/scidavis/files/1176991/python_code_to_run_in_SciDAVis.txt)
UPDATE:
the time.sleep() function uses the time in seconds, so you only need to convert minutes in seconds to adapt it to you case.

**Comment by SimoneTosato** [comment]
I will share this on your forum if i find out how to imporve it. Thank you
