### ISSUE TITLE
Copy and Export graph layer is not working properly

### ISSUE THREAD

**Issue by Fellypao** [highperformancecoder/scidavis-old#56]
_Reporting here because the bug report page at SF was not working at the moment of the submission (error 404 :-P )._

If you try to copy or export a layer from a graph it will not work properly. The attached figure shows the problem.
This was verified in SciDAVis 1.19 and 1.21 under Slackware 14.2 (32-bits) and in SciDAVis 1.21 under WINE.
To reproduce the issue:
1 - create a graph;
2 - right click on it;
3 - select copy or export;
4 - select layer;
5 - paste (for copy) or save (for export) the figure -> it will be cut or empty.

Notice that to export/copy the window is working fine.

![test-export_layer-1d21](https://user-images.githubusercontent.com/16227753/30866545-f9700c80-a2af-11e7-9a0e-b9a0ed215e50.png)

[test-export_layer.sciprj.zip](https://github.com/highperformancecoder/scidavis/files/1333564/test-export_layer.sciprj.zip)

**Comment by highperformancecoder** [comment]
SourceForge is back up now...

**Comment by Fellypao** [comment]
Copied there. Closing here :-)
