### ISSUE TITLE
Porting to Python 3

### ISSUE THREAD

**Issue by alxpl** [highperformancecoder/scidavis-old#69]
Hello,

It was brought to our attention on the Fedora devel mailing list that the Python 2.x branch, which had been maintained by the community, will be deprecated. We were advised to notify upstream projects that use Python 2.x code about this and there is an intention to drop every python2-* package/subpackage by Fedora 30.
There is a pretty thorough ["Conservative Python 3 Porting Guide"](https://portingguide.readthedocs.io/en/latest/) and after running the python-modernize tool mentioned in it, it seems that Python code in SciDAVis needs very little work, mainly some print and include statements that need to be restructured. I haven't written anything in Python in over a decade and I saw that there are a number of PyObject references in scidavis.sip, PythonScripting.h, PythonScript.h, PythonScripting.cpp and PythonScript.cpp, but I am not in a position to say what needs to change - if anything - with regard to C stuff. On the plus side, PyQt4 already supports Python 3.

Anyway, this is a heads up, I hope I haven't ruined anyone's day.

Best regards
Alex

**Comment by highperformancecoder** [comment]
On Thu, Apr 26, 2018 at 07:12:34AM +0000, alxpl wrote:
> Hello,
> 
> It was brought to our attention on the Fedora devel mailing list that the Python 2.x branch, which had been maintained by the community, will be deprecated. We were advised to notify upstream projects that use Python 2.x code about this and there is an intention to drop every python2-* package/subpackage by Fedora 30.
> There is a pretty thorough ["Conservative Python 3 Porting Guide"](https://portingguide.readthedocs.io/en/latest/) and after running the python-modernize tool mentioned in it, it seems that Python code in SciDAVis needs very little work, mainly some print and include statements that need to be restructured. I haven't written anything in Python in over a decade and I saw that there are a number of PyObject references in scidavis.sip, PythonScripting.h, PythonScript.h, PythonScripting.cpp and PythonScript.cpp, but I am not in a position to say what needs to change - if anything - with regard to C stuff. On the plus side, PyQt4 already supports Python 3.

Well, yes - it is on our list of proposed refactorings. The trouble
is, that before embarking on any successful refactoring, we really
need decent test coverage to catch most of the inevitable
breakages. Currently, I'm working on getting test coverage up - so far
it is at around 30%, but it is slow work for such a sprawling
database. 

I gather Fedora 30 is approximately a year away. There is also
pressure to move to QT5 from some distros also.

Personally, we can only move as fast as we have resources to do, and
ignore artificial deadlines from the distros. To be quite frank, we
have been trying to bring SciDaVis up to modern versions for the last
3-4 years, so even a year's headsup looks too tight to me. I will
always make SciDaVis for upcoming distros through OBS, and if that
requires interim support from an obsolete package, then I'll supply
those too.

> 
> Anyway, this is a heads up, I hope I haven't ruined anyone's day.
> 
> Best regards
> Alex
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/scidavis/issues/69

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by alxpl** [comment]
I re-read the entire discussion and I think that some of the finer points regarding the timeline may have been lost on me, so in order to avoid any misinformation, [here](https://lists.fedorahosted.org/archives/list/devel@lists.fedoraproject.org/thread/2XDT6S62SEN4KGWQCOUYKXLBYVTKJ5VI/) is the original thread.

> Personally, we can only move as fast as we have resources to do, and ignore artificial deadlines from the distros.

I will try to catch up on Python 3 and see if I can lend a hand with porting. If I can't get any results by the release of F29, I will reach out to our Python SIG for help (though obviously, I can not promise the timely help of others).

**Comment by highperformancecoder** [comment]
On Mon, Apr 30, 2018 at 07:55:53AM +0000, alxpl wrote:
> I will try to catch up on Python 3 and see if I can lend a hand with porting. If I can't get any results by the release of F29, I will reach out to our Python SIG for help (though obviously, I can not promise the timely help of others).

I appreciate any help given. Right now, the best help you could give
would be to generate python scripts exercising different parts of the
scidavis API. I'm still a relative neophyte when it comes to Python,
so this would be a big help. These script currently live in the
test/pythonTests, so you can see how the existing ones are done. The
scidavis python API is documented in the file
libscidavis/src/scidavis.sip, although there is partial documentation
also in the manual

scidavis will now run a Python script directly from the command line,
and exit that script with code 0 if app.exit() is called. Failing a
test involves throwing an exception - using the python assert
statement is perhaps the most convenient way of doing that. And
obviously an expected exception can be caught using a try/except block.

Finally, moving to Python 3 will involve a version bump for SciDaVis
to 2.x, so we needn't be worried about feature for feature emulation
of python 2 vs python 3. We just want to make sure that functionality
is equivalent.

The same will be true of the move to Qwt6 and Qt5. It would be kind of
nice to get all of these done in the one version bump, but ultimately,
if scidavis suddenly jumps to version 4 over a short space of time,
then that is not a biggie either.

Cheers
-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by Fellypao** [comment]
Off-topic (but not so much...):
Since we can have more than one person working on the same subject, what about to register the contribution plans as a SciDAVis TODO ticket at https://sourceforge.net/p/scidavis/scidavis-todo/ in order to avoid duplicated works?
I've just registered my plans there :-)

Best regards

**Comment by highperformancecoder** [comment]
Good idea. Also, use the ownership field to take ownership of a ticket
you're working on. If you see someone owning a ticket that you'd like
to work on, but not much activity, then please reach out to that
person to ask what's going on.

I'll use my project maintainer status to follow up on anything that's
gone too stagnant.

Cheers
-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by alxpl** [comment]
I have created a ticked, but I could not take ownership, as my name was not listed in the drop-down menu. What do I need to do?

I looked through my old files and the last time I had written something from scratch in Python, it was at 2.3-2.4. I picked up a book on the latest version and I'm going over things whenever I've got dead time at the lab, essentially treating it as a new language, so it will be a while before I touch any code.

**Comment by Fellypao** [comment]
@alxpl ,
You need write access on scidavis project at sf to take ownership of an issue. The former developers gave me it in the past so I could update the pt-br translation.

**Comment by highperformancecoder** [comment]
Hi Alex,

I have given you developer priveleges on SciDaVis sourceforge
project. You should now be able to edit tickets.

Welcome to the project!

PS Miquel Garriga has just created a pull request with some Python 3 stuff, so
give me 24 hours to review... :).

Cheers

On Thu, May 03, 2018 at 11:10:51PM -0700, alxpl wrote:
> I have created a ticked, but I could not take ownership, as my name was not listed in the drop-down menu. What do I need to do?
> 
> I looked through my old files and the last time I had written something from scratch in Python, it was at 2.3-2.4. I picked up a book on the latest version and I'm going over things whenever I've got dead time at the lab, essentially treating it as a new language, so it will be a while before I touch any code.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/scidavis/issues/69#issuecomment-386513163

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by alxpl** [comment]
Hello @highperformancecoder,

> I have given you developer priveleges on SciDaVis sourceforge project. You should now be able to edit tickets.

I've logged out and back into sf.net, cleared cache & cookies, tried a different browser, but I see no option to edit anything. What's more, the [documentation page about project permissions](https://sourceforge.net/p/forge/community-docs/Project%20Permissions/) throws a 403 error… If I try to open a new ticket, I do have the option to select myself in the drop-down menu and in the "Me" menu on the top right there is a link to SciDAVis project page. Do I need to do something else before I can edit the ticket?

> Welcome to the project!

Thank you!

> PS Miquel Garriga has just created a pull request with some Python 3 stuff, so give me 24 hours to review... :).

The last visible pull request is "Dropqt3". Is it because of the recent changes GitHub implemented?

**Comment by highperformancecoder** [comment]
I just changed the ownership of the ticket to you, so that part is
obviously working.

To edit a ticket, there should be an icon on the ticket title line
that looks like a pencil, with the word "Edit".

If you're not getting that, then you might need to raise a ticket with
the SourceForge folks.

On Sat, May 05, 2018 at 07:06:34AM +0000, alxpl wrote:
> Hello @highperformancecoder,
> 
> > I have given you developer priveleges on SciDaVis sourceforge project. You should now be able to edit tickets.
> 
> I've logged out and back into sf.net, cleared cache & cookies, tried a different browser, but I see no option to edit anything. What's more, the [documentation page about project permissions](https://sourceforge.net/p/forge/community-docs/Project%20Permissions/) throws a 403 error… If I try to open a new ticket, I do have the option to select myself in the drop-down menu and in the "Me" menu on the top right there is a link to SciDAVis project page. Do I need to do something else before I can edit the ticket?
> 
> > Welcome to the project!
> 
> Thank you!
> 
> > PS Miquel Garriga has just created a pull request with some Python 3 stuff, so give me 24 hours to review... :).
> 
> The last visible pull request is "Dropqt3". Is it because of the recent changes GitHub implemented?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/scidavis/issues/69#issuecomment-386785377

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by alxpl** [comment]
Filed ticket [#17634](https://sourceforge.net/p/forge/site-support/17634/).

**Comment by alxpl** [comment]
Given the amount of Python patches in the last day I feel this is pointless, but sf support has requested that you chime in the ticket above.

**Comment by highperformancecoder** [comment]
It looks like the OpenSUSE repo is back in business, so I should be
able to check Miquel's python3 commits today...

On Mon, May 07, 2018 at 09:12:56PM +0000, alxpl wrote:
> Given the amount of Python patches in the last day I feel this is pointless, but sf support has requested that you chime in the ticket above.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/scidavis/issues/69#issuecomment-387208286

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by highperformancecoder** [comment]
Python3 stuff is all golden, AFAICS

**Comment by alxpl** [comment]
After struggling with the Python3 dependencies and paths for the last couple of days, I've reached a point were the f28 build fails with this (complete logs [here](https://koji.fedoraproject.org/koji/taskinfo?taskID=27962914)):
```
make[1]: Entering directory '/builddir/build/BUILD/scidavis-master/scidavis'
python -m py_compile scidavisrc.py
make[1]: Leaving directory '/builddir/build/BUILD/scidavis-master/scidavis'
make[1]: python: Command not found
make[1]: *** [Makefile:205: scidavisrc.pyc] Error 127
```

In the %build section of my spec file I have:
```
export PYTHON=python3
%if 0%{?__isa_bits} == 64
%qmake_qt4 PRESET=linux_package libsuff="64" CONFIG+=aegis CONFIG+=python
%else
%qmake_qt4 PRESET=linux_package CONFIG+=aegis CONFIG+=python
%endif
%make_build
```
Isn't this how I was supposed to set python3 as the preferred python interpreter?

I used the current master snapshot as source.
This is my [spec file](https://alexpl.fedorapeople.org/packages/SciDAVis/w_py3/scidavis.spec) and here is the [source rpm](https://alexpl.fedorapeople.org/packages/SciDAVis/w_py3/scidavis-1.23-4.fc28.src.rpm).

For the sake of comparison, [here](https://koji.fedoraproject.org/koji/buildinfo?buildID=1097664) is the current 1.23 build (rpms, logs and everything), which is still using python2.

Am I doing something blatantly wrong?


P.S.: The combination of Python 3.7 and PyQt is bound to be even more fun…

**Comment by hroncok** [comment]
As for Fedora:

> `make[1]: python: Command not found`

This means the Makefile is calling `python` or something that's calling `python`. `python` is not Python 3 but Python 2.

1) try to locate where is `python` called and patch/sed it out for `python3` (or use a configure option etc.)
2) if it doesn't help or you cannot locate it, a trick is to put a symbolic link to `/usr/bin/python3` called `python` to a temporary directory and `export PATH=/path/to/whatnot:$PATH` before the build. that's ugly but should workaround the problem.

Note that the  [Move /usr/bin/python into a separate package](https://fedoraproject.org/wiki/Changes/Move_usr_bin_python_into_separate_package) change was not yet deployed in Fedora and will be only deployed to Rawhide anyway. However if your package doesn't BR python2, it usually doesn't get `/usr/bin/python` either (unless it's brought in transitively).

**Comment by gbm19** [comment]
Please try attached patch. 
[fix-compile-in-python3-only-dists.patch.txt](https://github.com/highperformancecoder/scidavis/files/2151743/fix-compile-in-python3-only-dists.patch.txt)

**Comment by alxpl** [comment]
Hi @gbm19,

This is after applying the patch:
```
make[1]: Entering directory '/builddir/build/BUILD/scidavis-master/scidavis'
m py_compile scidavisrc.py
make[1]: m: Command not found
make[1]: [Makefile:205: scidavisrc.pyc] Error 127 (ignored)
make[1]: Leaving directory '/builddir/build/BUILD/scidavis-master/scidavis'
make[1]: Entering directory '/builddir/build/BUILD/scidavis-master/scidavis'
m py_compile scidavisUtil.py
make[1]: m: Command not found
make[1]: [Makefile:208: scidavisUtil.pyc] Error 127 (ignored)
```
For some reason PYTHONBIN is empty and python3 never makes it there… For good measure, I added python3 to the build requirements, but that didn't help either. In the end I forcefully patched "python3" in python.pri to see if there was anything else amiss.

The compilation continues (since the error is ignored) and it fails a little later because I hadn't noticed the dependencies brought in by the new tests. This struck me as odd, because I have testing disabled in the spec file:

```
%check
desktop-file-validate %{buildroot}/%{_datadir}/applications/%{name}.desktop
appstream-util validate-relax --nonet %{buildroot}%{_datadir}/appdata/*.appdata.xml
# Enable when building locally
#cd test && xvfb-run -a ./unittests
```

Anyway, I am adding them now one by one (so far I've got boost-devel and  unittest-cpp-devel). If I notice anything else python-related, I will report back.

All my best for now

**Comment by alxpl** [comment]
> so far I've got boost-devel and unittest-cpp-devel

Ok, it was just those two.
Tomorrow I'll give python 3.7 a try.

**Comment by highperformancecoder** [comment]
On Sat, Jun 30, 2018 at 01:46:38PM -0700, alxpl wrote:
> 
> Anyway, I am adding them now one by one (so far I've got boost-devel and  unittest-cpp-devel). If I notice anything else python-related, I will report back.

For distributions, you should use CONFIG+=python CONFIG+=origin

CONFIG+=aegis also builds the regression test suite, but that is not
necessary for distributions, and eliminates the dependency on
unittest++ and boost-regex


-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by alxpl** [comment]
Are all the tests still run by calling the unittests executable?

**Comment by alxpl** [comment]
I submitted a build in a side tag with Python 3.7 in fedora rawhide, which failed with this error:

```
g++ -c -pipe -std=c++0x -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_REENTRANT -Wall -W -fPIC -DSCRIPTING_CONSOLE -DSCRIPTING_DIALOG -DORIGIN_IMPORT -DQT_PLUGIN -DTS_PATH=\"/usr/share/scidavis/translations\" -DDOC_PATH=\"/usr/share/doc/scidavis\" -DPLUGIN_PATH=\"/usr/lib/scidavis/plugins\" -DLEGACY_CODE_0_2_x -DSCRIPTING_MUPARSER -DPYTHON_CONFIG_PATH=\"/usr/../usr/lib64/python3.7/site-packages/scidavis\" -DPYTHON_UTIL_PATH=\"/usr/../usr/lib64/python3.7/site-packages/scidavis\" -DSCRIPTING_PYTHON -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtOpenGL -I/usr/include/QtXml -I/usr/include/QtSvg -I/usr/include -I/builddir/usr/include -I/usr/include/qwt5-qt4 -I/usr/include/qwtplot3d -I/usr/include/muParser -I../scidavis -I../3rdparty/liborigin -Isrc -Isrc/future -I/usr/include/python3.7m -I-I/usr/include/python3.7m -I/usr/X11R6/include -I../tmp/scidavis -I. -o ../tmp/libscidavis/PythonScripting.o src/PythonScripting.cpp
src/PythonScripting.cpp: In member function 'QString PythonScripting::errorMsg()':
src/PythonScripting.cpp:179:61: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
    if (frame->f_code->co_name && *(fname = PYSTRING_AsString(frame->f_code->co_name)) != '?')
                                                             ^
make[1]: *** [Makefile:3675: ../tmp/libscidavis/PythonScripting.o] Error 1
```

I think this has to do with PyString_AsString changing from python2 to python3.3 and again in python3.7:
http://py3c.readthedocs.io/en/latest/reference.html#c.PyStr_AsString
https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AsUTF8

**Comment by hroncok** [comment]
It's const char *. Either cast it or change fname to be const as well.

**Comment by gbm19** [comment]
Attached patch to fix
[fix-for-python3.7.patch.txt](https://github.com/highperformancecoder/scidavis/files/2153021/fix-for-python3.7.patch.txt)
 "invalid conversion from 'const char*' to 'char *'" compile error.

**Comment by alxpl** [comment]
> Attached patch to fix
> fix-for-python3.7.patch.txt
> "invalid conversion from 'const char*' to 'char *'" compile error.

One [build](https://koji.fedoraproject.org/koji/taskinfo?taskID=27977794) with python3.6 and [another](https://koji.fedoraproject.org/koji/taskinfo?taskID=27977784) with python3.7 were both successful.

**Comment by gbm19** [comment]
Sorry for the noise. Attached patch replaces previous two and should fix the empty PYTHONBIN problem. In qmake  "$$(variable)" syntax is for environment variables. Normal variables use "$$variable".
The patch is against current git HEAD.
[fix-compile-in-python3-only-dists-v2.patch.txt](https://github.com/highperformancecoder/scidavis/files/2153166/fix-compile-in-python3-only-dists-v2.patch.txt)

**Comment by alxpl** [comment]
The fact that shebang lines could be omitted had completely disappeared from my memory, I patched everything to python3 instead.

Everything is fine now, well done once again!
