### ISSUE TITLE
src/MuParserScripting.h: 2 * infinite recursion ?

### ISSUE THREAD

**Issue by dcb314** [highperformancecoder/scidavis-old#7]
1.

src/MuParserScripting.h:87:7: warning: all paths through this function will call itself [-Winfinite-recursion]

```
static double ceil(double x)
  { return ceil(x); }
```

2.

src/MuParserScripting.h:89:7: warning: all paths through this function will call itself [-Winfinite-recursion]

```
static double floor(double x)
  { return floor(x); }
```

**Comment by highperformancecoder** [comment]
fixed.
