### ISSUE TITLE
Logo design: scidavis

### ISSUE THREAD

**Issue by baranpirincal** [highperformancecoder/scidavis-old#75]
Hey, I examined your project and I realized that your project has no logo design yet. What do you think about it? I am graphic designer and my main purposes are make my portfolio better with supporting open source projects in field of graphics. If you interested we can talk about design decisions or ideas. I am waiting your feedback, have a nice day!

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by highperformancecoder** [comment]
SciDaVis already has a logo, several in fact:
https://github.com/highperformancecoder/scidavis/blob/master/scidavis-logo.svg, which is used on the website, and
https://github.com/highperformancecoder/scidavis/blob/master/scidavis/icons/scidavis.svg, which is the icon used on the desktop.

However, there is another project I'm involved in that could use some professional graphics design.  
https://github.com/highperformancecoder/minsky

Might you be interested in contributing to that?

**Comment by baranpirincal** [comment]
@highperformancecoder Of course, where can we talk about design,ideas and drafts?
Do you have an idea for logo design of minsky or do you want me to use something on logo design?

**Comment by highperformancecoder** [comment]
How about opening an issue on the Minsky project, and we can chat there? Obviously, your first task will be to download a copy and check out the existing logos and icons. There's binaries for Windows, Mac or even a range of Linux distros, so you should be up and running pretty quickly.
