### ISSUE TITLE
Core dump when saving project file with colors from the picker (on Fedora 28)

### ISSUE THREAD

**Issue by alxpl** [highperformancecoder/scidavis-old#79]
Hello,

Yesterday I built 1.23 packages for Fedora [27](https://koji.fedoraproject.org/koji/taskinfo?taskID=27419617), [28](https://koji.fedoraproject.org/koji/taskinfo?taskID=27419615) and [rawhide](https://koji.fedoraproject.org/koji/taskinfo?taskID=27419613) (check the links for detailed build logs, rpms and source rpms) and submitted them as updates (a few hours ago they landed in testing - note to self, I should probably unpush them). Today I realized that there is a problem, after spending some time on an existing project file and trying to save it.

To cut to the chase, this is how I can reproduce the crash:

1. Create a new project file or open an existing one.
2. Plot something (I had line plots).
3. Change the line color by choosing something from the picker.
4. Save the project.

At this point SciDAVis crashes and I am left with an "intended_filename.sciprj.new" file at the chosen location. When I open that file (open with, etc.), I get two SciDAVis windows, one empty (like a new project) and another which contains an empty plot and a table with "SciDAVis 1.23" as the title of a column with 9 cells, each containing a zero, except for the fourth one, which contains something like "1.14971e+06". If I try to open the file from inside SciDAVis, I get a message that this is not a valid project file.

I've looked at the builders' logs and as far as I can tell, at least all the qt-related dependencies are on the same version across f27, f28 & f29, so I'd expect the same behavior in all of them. The following is an excerpt from the root.log in rawhide:

```
Installing:
 PyQt4-devel             x86_64 4.12.1-7.fc29                       build 441 k
 desktop-file-utils      x86_64 0.23-8.fc29                         build  79 k
 doxygen                 x86_64 1:1.8.14-2.fc28                     build 6.5 M
 gsl-devel               x86_64 2.4-3.fc27                          build 563 k
 libappstream-glib       x86_64 0.7.9-1.fc29                        build 328 k
 muParser-devel          x86_64 2.2.5-6.fc29                        build  31 k
 python2-devel           x86_64 2.7.15-2.fc29                       build 410 k
 python2-sip-devel       x86_64 4.19.9-0.1.dev1805261119.fc29       build 183 k
 qt-assistant-adp-devel  x86_64 4.6.3-17.fc29                       build  13 k
 qt-devel                x86_64 1:4.8.7-38.fc29                     build  11 M
 qwt5-qt4-devel          x86_64 5.2.2-34.fc29                       build 301 k
 qwtplot3d-qt4-devel     x86_64 0.2.7-28.fc28                       build  98 k
 zlib-devel              x86_64 1.2.11-8.fc29                       build  55 k
```

If anyone needs them, I have uploaded a [stack trace](https://alexpl.fedorapeople.org/bugs/SciDAVis/1.23_20180605/sc_stack_trace) from gdb and the [core dump](https://alexpl.fedorapeople.org/bugs/SciDAVis/1.23_20180605/sc.coredump).

Can anyone else confirm this? Should I report this to our Qt maintainers and if yes, which of all the Qts is responsible (if Qt is indeed to blame)?

Best regards,
Alex

**Comment by alxpl** [comment]
I've fiddled with the .sciprj.new files a bit more and apparently if I remove the .new part, SciDAVis doesn't complain. If they come from a new project, they contain the tables, but no graph. If they are from a save on top of an existing project, they are identical to the original project file also without graphs. In the later case they lack any tables that had been added to the project between saves.

**Comment by gbm19** [comment]
I could not reproduce the crash in my system (Fedora 27, gcc 7.3.1, python3).
However, your "stack trace" points to a bug in std::find call in ColorBox::colorIndex called in Graph::saveCurveLayout. 
This bug is a side effect of PR #68. Attached patch should fix it. 
Besides, it includes code to improve color-selection for symbol edge and fill, replacing colorlists (ColorBox) with color picker (ColorButton).
If the patch fixes your crash I will prepare a PR

[fix-crash-when-saving-rgba-line-colors.patch.txt](https://github.com/highperformancecoder/scidavis/files/2078384/fix-crash-when-saving-rgba-line-colors.patch.txt)

**Comment by alxpl** [comment]
You are my hero, that did the trick. Before you replied I had gotten around to test it on f28.i686 and f29.x86_64, they all experienced the same issue. I have built new packages and submitted updates for all versions.
I suppose you should go ahead and file the PR.

> However, your "stack trace" points to a bug in […]
I didn't get it right? Is something missing?
