### ISSUE TITLE
Crashes in project explorer

### ISSUE THREAD

**Issue by Rugaliz** [highperformancecoder/scidavis-old#90]
When i right click inside the project explorer outside the icon for folders area, scidavis crashes with a segmentation fault.
I tested this using fedora 28

**Comment by Fellypao** [comment]
I can reproduce the crash here - on both Slackware and Windows - SciDAVis 1.23

**Comment by alxpl** [comment]
In fedora, the automatic bug reporting tool says this:

`Process 24158 (scidavis) crashed in QMenu::exec(QPoint const&, QAction*)()`

I ran it through gdb, in case anyone finds that useful.

[gdb_backtrace.txt](https://github.com/highperformancecoder/scidavis/files/2245542/gdb_backtrace.txt)

**Comment by gbm19** [comment]
Attached patch solves the problem for me (fedora 27)

[fix-gh-issue-90.patch.txt](https://github.com/highperformancecoder/scidavis/files/2247001/fix-gh-issue-90.patch.txt)

**Comment by alxpl** [comment]
Tested and working on f28, didn't notice any side effects.
I will submit updates for f27 & f28 as soon as the builds are ready.

**Comment by Fellypao** [comment]
The patch works on Slackware too.
Good job.

**Comment by highperformancecoder** [comment]
Patch merged.
