### ISSUE TITLE
Suggestion to avoid bug reports as github issues

### ISSUE THREAD

**Issue by Fellypao** [highperformancecoder/scidavis-old#92]
I got this idea when I tried to open an issue for scikit-learn: 
https://github.com/scikit-learn/scikit-learn/issues
where a default message is shown when someone start a new issue.

My suggestion is to leave a default message like:
"If you want to report a bug you've found in SciDAVis, please, open a ticket at https://sourceforge.net/p/scidavis/scidavis-bugs/"

Add also other message(s) describing the kind of issues can be reported at github...

Note: I don't know how to add a default message for new issues.

**Comment by alxpl** [comment]
> Note: I don't know how to add a default message for new issues.

In the repository settings you can set up templates for issues.

**Comment by highperformancecoder** [comment]
On Tue, Aug 07, 2018 at 08:01:16AM -0700, alxpl wrote:
>     Note: I don't know how to add a default message for new issues.
> 
> In the repository settings you can set up templates for issues.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

I agree, and will look into it. I think there is value in having all the issues reported in the one place, and for now, until, or unless we move the existing ticket data onto Github holus bolus, that place is SourceForge. I would like it if SourceForge could fix their editor pane though - the number of times I've lost data through pasting something into it makes me very nervous using it :).

Cheers

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by highperformancecoder** [comment]
Issue templates have now been created.
